name: A workflow that describes on its own
on: push
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Show repository name, the branch name, the commit id, event name and runner os
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.re_name }}"
          echo "Commit: ${{ github.sha }}"
          echo "Event: ${{ github.event_name }}"
          echo "Runner OS: ${{ runner.os }}"
